FROM golang:1.19.2-alpine as builder

RUN apk add --no-cache make

WORKDIR /app

COPY . .

RUN make build

# ---

FROM alpine:3.15

COPY --from=builder /app/build /usr/bin

CMD sh -c "allgor --port=$PORT --playground=$PLAYGROUND"