version: '3'
services:
  allgor-backend:
    container_name: allgor-backend
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    ports:
      - $ALLGOR_PORT:$ALLGOR_PORT
  sonarqube:
    container_name: sonarqube
    image: sonarqube
    ports:
      - 9000:9000
