FROM golang:1.19.2-alpine AS builder

RUN apk add --no-cache make

WORKDIR /app

COPY . .

RUN make build

# ---

FROM alpine:3.15

COPY --from=builder /app/build /usr/bin

RUN addgroup -S nonroot \
  && adduser -S nonroot -G nonroot

USER nonroot

ENV ALLGOR_PLAYGROUND=false
ENV ALLGOR_PORT=5000

ENTRYPOINT ["allgor"]