package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.25

import (
	"context"
	"fmt"

	graphqlgenerated "github.com/allgor-data/backend/graphql/generated"
)

// CreateTodo is the resolver for the createTodo field.
func (r *mutationResolver) CreateTodo(ctx context.Context, input graphqlgenerated.NewTodo) (*graphqlgenerated.Todo, error) {
	panic(fmt.Errorf("not implemented: CreateTodo - createTodo"))
}

// Todos is the resolver for the todos field.
func (r *queryResolver) Todos(ctx context.Context) ([]*graphqlgenerated.Todo, error) {
	panic(fmt.Errorf("not implemented: Todos - todos"))
}

// Mutation returns graphqlgenerated.MutationResolver implementation.
func (r *Resolver) Mutation() graphqlgenerated.MutationResolver { return &mutationResolver{r} }

// Query returns graphqlgenerated.QueryResolver implementation.
func (r *Resolver) Query() graphqlgenerated.QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
